baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Home'
pygmentsStyle = "dracula"

[permalinks]
  blog = "/:filename/"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 2

[params]
  dateFormat = "Jan 2, 2006"
