baseURL = "https://ikatzarski.com/"
languageCode = "en-us"
title = "ikatzarski's Blog"

pygmentsStyle = "dracula"

[permalinks]
  blog = "/:filename/"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 2

[params]
  dateFormat = "Jan 2, 2006"
  description = "Ivan Katzarski's blog about Software Engineering, DevOps, tech, and who knows what else."
